s3-to-speakers:
    python3.9 serial_to_stdout.py | \
    ffplay -nodisp -autoexit -f s16le -ar 16000 -af "atrim=start=0.5,asetpts=N/SR/TB,highpass=f=300" -

s3-to-speakers-compressor:
    python3.9 serial_to_stdout.py --port /dev/cu.usbmodem2101 \
    | ffplay -f s16le -ar 16000 -i - \
      -af "highpass=f=80,alimiter=limit=0.90:level=disabled,acompressor=threshold=-10dB:ratio=6:attack=0.5:release=40"

s3-to-video:
    python3.9 serial_to_stdout.py --port /dev/cu.usbmodem2101 \
    | ffplay -f s16le -ar 16000 -i -

s3-record:
    python3.9 serial_to_stdout.py \
    | ffmpeg -y -f s16le -ar 16000 -ac 1 -i - \
      -af "atrim=start=0.5,asetpts=N/SR/TB" \
      -c:a pcm_s16le mic.wav